# Permalinks
permalink:        		/to/:categories/:title
relative_permalinks: 	true

# Setup
title:            		Pixie Goes
tagline:          		'Lorem Ipsum'
url:              		http://pixiegoes.com
paginate:         		8
baseurl:          		/
author:
name:           		Ceara Pixie
url: 					https://twitter.com/pixiegoes
email:					pixiegoes@gmail.com

# Custom vars
version:          		1.0.0
github:
  repo:					https://github.com/pixiegoes/pixiegoes.github.io

# Images
banner_image:			sorrento.jpg

#gems
gems: 					['jekyll-less']
