# Permalinks
permalink:        		/to/:title

# Setup
title:            		Pixie goes...
tagline:          		'Lorem Ipsum'
url:              		http://pixiegoes.com
paginate:         		8
baseurl:          		""
author:
name:           		Ceara Pixie
twitter_username:		pixiegoes
email:					pixiegoes@gmail.com
instagram_username:		pixiecg
gems:                 [jekyll-paginate]


description: > # this means to ignore newlines until "baseurl:"
  A lifestyle blog giving you tips and advice on how to make the most of London and beyond!

# Build settings
markdown: kramdown
